import type { ReactNode } from "react";
import { Sparkles } from "lucide-react";
import type { DeckSlide, PresentationMeta } from "@/lib/presentation-types";

export interface SlideComponentProps {
  slide: DeckSlide;
  index: number;
  total: number;
  meta: PresentationMeta;
}

interface SlideFrameProps {
  meta: PresentationMeta;
  index: number;
  total: number;
  kicker?: string;
  title?: string;
  centered?: boolean;
  accent?: boolean;
  children: ReactNode;
}

export function SlideFrame({
  meta,
  index,
  total,
  kicker,
  title,
  centered = false,
  accent = false,
  children,
}: SlideFrameProps) {
  const hasHeader = Boolean(kicker || title);

  return (
    <div
      className={`flex min-h-[420px] w-full flex-col overflow-hidden rounded-xl border border-border-subtle bg-surface shadow-lg lg:aspect-video lg:min-h-0 ${
        accent ? "border-t-4 border-t-primary" : ""
      }`}
    >
      {hasHeader ? (
        <header className="flex items-end justify-between gap-4 border-b border-border-subtle px-8 pb-4 pt-6">
          <div>
            {kicker ? (
              <p className="text-[11px] font-semibold uppercase tracking-widest text-primary">
                {kicker}
              </p>
            ) : null}
            {title ? (
              <h2 className="mt-1 text-2xl font-bold tracking-tight text-foreground">
                {title}
              </h2>
            ) : null}
          </div>
          <span className="shrink-0 font-mono text-xs text-muted-foreground">
            {index + 1} / {total}
          </span>
        </header>
      ) : null}

      <div
        className={`flex-1 overflow-y-auto px-8 py-6 ${
          centered
            ? "flex flex-col items-center justify-center text-center"
            : ""
        }`}
      >
        {children}
      </div>

      <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-border-subtle px-8 py-3 text-[11px] text-muted-foreground">
        <span className="inline-flex items-center gap-1.5">
          <Sparkles className="h-3 w-3 text-primary" />
          Generated by {meta.generatedBy} · {meta.documentsAnalyzed} ·{" "}
          {meta.analysisPeriod} · {meta.confidence}% confidence
        </span>
        <span>{meta.classification}</span>
      </footer>
    </div>
  );
}
