import { Badge } from "@/components/badge";
import type { BadgeTone } from "@/components/badge";
import { ReportSection } from "@/components/reports/report-section";
import { ReportTable } from "@/components/reports/report-table";
import type { ReportRecommendation, Severity } from "@/lib/report-types";

const priorityTone: Record<Severity, BadgeTone> = {
  Critical: "rose",
  High: "amber",
  Medium: "blue",
  Low: "emerald",
};

interface AiRecommendationsSectionProps {
  data: ReportRecommendation[];
}

export function AiRecommendationsSection({
  data,
}: AiRecommendationsSectionProps) {
  return (
    <ReportSection
      number="8"
      title="AI Recommendations"
      description="Prioritized recommendations generated by Risk Copilot AI, ordered by estimated risk impact."
    >
      <ReportTable
        columns={[
          {
            header: "Priority",
            render: (row) => (
              <Badge tone={priorityTone[row.priority]}>{row.priority}</Badge>
            ),
          },
          {
            header: "Recommendation",
            render: (row) => (
              <span className="font-medium text-foreground">{row.action}</span>
            ),
          },
          { header: "Category", render: (row) => row.category },
          {
            header: "Estimated impact",
            render: (row) => (
              <span className="font-medium text-emerald-600 dark:text-emerald-400">
                {row.impact}
              </span>
            ),
          },
        ]}
        rows={data}
      />
    </ReportSection>
  );
}
