import type { ReportMeta } from "@/lib/report-types";

interface ReportFooterProps {
  meta: ReportMeta;
}

export function ReportFooter({ meta }: ReportFooterProps) {
  return (
    <footer className="border-t border-border-subtle pt-6">
      <div className="flex items-start justify-between gap-6">
        <div className="text-sm">
          <p className="font-semibold text-foreground">Prepared by</p>
          <p className="text-muted-foreground">{meta.preparedBy}</p>
        </div>
        <div className="text-right text-sm">
          <p className="font-semibold text-foreground">Approved by</p>
          <p className="text-muted-foreground">{meta.approvedBy}</p>
        </div>
      </div>
      <p className="mt-6 text-xs leading-relaxed text-muted-foreground">
        This report was generated by {meta.generatedBy} from documents uploaded
        for the {meta.analysisPeriod} analysis cycle. It is provided for
        internal decision-making and must be verified before external
        distribution. Figures are illustrative and based on the uploaded risk
        register, audit findings, exception log and MIS reports.
      </p>
    </footer>
  );
}
