import { ShieldCheck, Sparkles } from "lucide-react";
import type { ReportMeta } from "@/lib/report-types";

interface ReportHeaderProps {
  meta: ReportMeta;
}

export function ReportHeader({ meta }: ReportHeaderProps) {
  return (
    <header>
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <ShieldCheck className="h-6 w-6" />
          </div>
          <div>
            <p className="text-lg font-bold text-foreground">{meta.bankName}</p>
            <p className="text-xs text-muted-foreground">
              Operational Risk Management
            </p>
          </div>
        </div>
        <span className="rounded border border-amber-500/40 bg-amber-50 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wider text-amber-700 dark:bg-amber-500/10 dark:text-amber-300">
          {meta.classification}
        </span>
      </div>

      <h1 className="mt-6 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
        {meta.reportTitle}
      </h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Reporting period · {meta.period}
      </p>

      <dl className="mt-6 grid grid-cols-2 gap-x-6 gap-y-3 text-sm sm:grid-cols-4">
        {[
          { label: "Report ID", value: meta.reportId },
          { label: "Issued", value: meta.issuedDate },
          { label: "Prepared by", value: meta.preparedBy },
          { label: "Approved by", value: meta.approvedBy },
        ].map((item) => (
          <div key={item.label}>
            <dt className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              {item.label}
            </dt>
            <dd className="mt-1 font-medium text-foreground">{item.value}</dd>
          </div>
        ))}
      </dl>

      <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg bg-surface-elevated px-4 py-3">
        <Sparkles className="h-4 w-4 shrink-0 text-primary" />
        <p className="text-xs text-muted-foreground">
          Generated by{" "}
          <span className="font-medium text-foreground">
            {meta.generatedBy}
          </span>{" "}
          · {meta.documentsAnalyzed} analyzed · Analysis period{" "}
          {meta.analysisPeriod} ·{" "}
          <span className="font-medium text-emerald-600 dark:text-emerald-400">
            {meta.confidence}% confidence
          </span>
        </p>
      </div>
    </header>
  );
}
