import type {
  ActivityItem,
  AuditFinding,
  Kpi,
  RiskTrendPoint,
} from "@/lib/types";

export const kpis: Kpi[] = [
  {
    id: "open-risks",
    label: "Open Risks",
    value: "342",
    change: "+4.2%",
    trend: "up",
    positive: false,
    sparkline: [308, 315, 309, 322, 328, 321, 335, 331, 340, 338, 342, 342],
  },
  {
    id: "high-risks",
    label: "High Risks",
    value: "57",
    change: "-3.1%",
    trend: "down",
    positive: true,
    sparkline: [72, 70, 68, 71, 65, 66, 63, 61, 64, 60, 59, 57],
  },
  {
    id: "audit-findings",
    label: "Audit Findings",
    value: "23",
    change: "+2 this month",
    trend: "up",
    positive: false,
    sparkline: [18, 19, 17, 20, 19, 21, 20, 22, 21, 24, 23, 23],
  },
  {
    id: "open-exceptions",
    label: "Open Exceptions",
    value: "12",
    change: "-1 this week",
    trend: "down",
    positive: true,
    sparkline: [19, 18, 18, 17, 16, 15, 15, 14, 14, 13, 13, 12],
  },
];

export const riskTrend: RiskTrendPoint[] = [
  { month: "Aug", open: 308, high: 72 },
  { month: "Sep", open: 315, high: 70 },
  { month: "Oct", open: 309, high: 68 },
  { month: "Nov", open: 322, high: 71 },
  { month: "Dec", open: 328, high: 65 },
  { month: "Jan", open: 321, high: 66 },
  { month: "Feb", open: 335, high: 63 },
  { month: "Mar", open: 331, high: 61 },
  { month: "Apr", open: 340, high: 64 },
  { month: "May", open: 338, high: 60 },
  { month: "Jun", open: 342, high: 59 },
  { month: "Jul", open: 342, high: 57 },
];

export const auditFindings: AuditFinding[] = [
  {
    id: "AF-2026-118",
    title: "Segregation of duties gaps in card onboarding",
    division: "Retail Banking",
    riskLevel: "High",
    status: "Open",
    owner: "M. Okafor",
    dueDate: "2026-08-14",
  },
  {
    id: "AF-2026-117",
    title: "End-of-day reconciliation exceptions not tracked",
    division: "Treasury Operations",
    riskLevel: "Medium",
    status: "In Progress",
    owner: "S. Alvarez",
    dueDate: "2026-08-21",
  },
  {
    id: "AF-2026-114",
    title: "Legacy system privileged access not recertified",
    division: "Technology",
    riskLevel: "High",
    status: "Overdue",
    owner: "D. Patel",
    dueDate: "2026-07-28",
  },
  {
    id: "AF-2026-112",
    title: "Vendor SLA monitoring lacking for core processors",
    division: "Procurement",
    riskLevel: "Medium",
    status: "In Progress",
    owner: "J. Lindqvist",
    dueDate: "2026-09-02",
  },
  {
    id: "AF-2026-109",
    title: "KYC refresh documents missing for 14 accounts",
    division: "Wealth Management",
    riskLevel: "Low",
    status: "Open",
    owner: "R. Kim",
    dueDate: "2026-08-30",
  },
  {
    id: "AF-2026-105",
    title: "Fraud alert false-positive tuning completed",
    division: "Financial Crime",
    riskLevel: "Medium",
    status: "Closed",
    owner: "T. Nakamura",
    dueDate: "2026-07-15",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "act-1",
    category: "exception",
    title: "Exception EX-2841 logged",
    description: "Vendor onboarding delay exceeding 30-day SLA in Procurement.",
    time: "12 min ago",
  },
  {
    id: "act-2",
    category: "risk",
    title: "Risk R-1092 re-rated to High",
    description: "Card fraud exposure raised after spike in unauthorized claims.",
    time: "48 min ago",
  },
  {
    id: "act-3",
    category: "audit",
    title: "Finding AF-2026-105 closed",
    description: "Fraud alert tuning evidence approved by Internal Audit.",
    time: "2 hr ago",
  },
  {
    id: "act-4",
    category: "report",
    title: "Monthly ORM MIS exported",
    description: "July Operational Risk MIS shared with the Board Risk Committee.",
    time: "5 hr ago",
  },
  {
    id: "act-5",
    category: "audit",
    title: "New audit finding added",
    description: "GIA raised finding on SWIFT user access reviews.",
    time: "Yesterday",
  },
  {
    id: "act-6",
    category: "exception",
    title: "Exception EX-2804 approved",
    description: "30-day temporary exception for KYC queue backlog approved.",
    time: "Yesterday",
  },
];
