import {
  auditFindings,
  boardSummary,
  executiveSummary,
  managementActions,
  reportMeta,
  riskOverview,
  riskScore,
} from "@/lib/report-data";
import type { Severity } from "@/lib/analysis-types";
import type {
  DeckSlide,
  PresentationAction,
  PresentationAuditFinding,
  PresentationMeta,
  PresentationStat,
} from "@/lib/presentation-types";

export const presentationMeta: PresentationMeta = {
  bankName: reportMeta.bankName,
  deckTitle: "Board Risk Review",
  deckId: "BRD-DECK-2026-07",
  period: reportMeta.period,
  preparedFor: "Board of Directors",
  preparedBy: reportMeta.preparedBy,
  date: reportMeta.issuedDate,
  classification: reportMeta.classification,
  generatedBy: reportMeta.generatedBy,
  documentsAnalyzed: reportMeta.documentsAnalyzed,
  analysisPeriod: reportMeta.analysisPeriod,
  confidence: reportMeta.confidence,
};

const presentationStats: PresentationStat[] = executiveSummary.stats;

const presentationActions: PresentationAction[] = managementActions.map(
  (action) => ({
    id: action.id,
    action: action.action,
    owner: action.owner,
    department: action.department,
    dueDate: action.dueDate,
    priority: action.priority,
    status: action.status,
  }),
);

const presentationFindings: PresentationAuditFinding[] = auditFindings.map(
  (finding) => ({
    id: finding.id,
    title: finding.title,
    division: finding.division,
    rating: finding.rating as Severity,
    status: finding.status,
    dueDate: finding.dueDate,
  }),
);

export const deckSlides: DeckSlide[] = [
  {
    id: "s1",
    shortTitle: "Title",
    notes:
      "Open by confirming the deck is generated by Risk Copilot AI from the 73 documents analyzed in the July cycle. State the headline: overall risk score improved to 82 (High).",
    content: {
      kind: "title",
      title: "Operational Risk Board Review",
      subtitle: "Monthly Risk Position — July 2026",
      preparedFor: "Board of Directors",
      presenter: "Sarah Chen — Operational Risk Manager",
      date: "August 6, 2026",
    },
  },
  {
    id: "s2",
    shortTitle: "Executive Summary",
    notes:
      "Walk through the four headline numbers. Emphasize the third consecutive monthly decline, but flag that nine critical findings remain open across identity and access and card onboarding.",
    content: {
      kind: "executive-summary",
      paragraph:
        "The overall operational risk score improved 6 points to 82 (High), the third consecutive monthly decline, driven by two high-risk closures in Financial Crime. Nine critical findings remain unresolved and three exceptions have exceeded the 30-day reporting threshold.",
      bullets: boardSummary.keyMessages.map((text) => ({ text })),
      stats: presentationStats,
    },
  },
  {
    id: "s3",
    shortTitle: "Risk Landscape",
    notes:
      "Note that critical exposure rose +2 this month even as the overall score improved. Point to Retail Banking (card fraud and onboarding) and Technology (legacy privileged access) as the concentration of exposure.",
    content: {
      kind: "risk-landscape",
      score: riskScore.score,
      level: riskScore.level,
      change: riskScore.change,
      description: riskScore.description,
      distribution: riskOverview.distribution.map((row) => ({
        severity: row.severity,
        count: row.count,
        share: row.share,
        change: row.change,
        positive: row.positive,
      })),
      trend: riskScore.history.map((point) => ({
        period: point.period,
        score: point.score,
      })),
      exposureAreas: riskOverview.exposureAreas,
    },
  },
  {
    id: "s4",
    shortTitle: "Top Risks",
    notes:
      "The top two risks are unchanged from June. Privileged access exposure ticked up with the August board deadline approaching; both are the subject of the remediation requests on the closing slide.",
    content: {
      kind: "top-risks",
      items: [
        {
          rank: 1,
          title: "Card fraud exposure",
          division: "Retail Banking",
          score: 92,
          severity: "Critical",
          likelihood: "Very likely",
          impact: "High",
          trend: "stable",
        },
        {
          rank: 2,
          title: "Legacy system privileged access",
          division: "Technology",
          score: 88,
          severity: "Critical",
          likelihood: "Very likely",
          impact: "High",
          trend: "up",
        },
        {
          rank: 3,
          title: "SWIFT user access reviews overdue",
          division: "Financial Crime",
          score: 79,
          severity: "High",
          likelihood: "Likely",
          impact: "High",
          trend: "stable",
        },
        {
          rank: 4,
          title: "Reconciliation exceptions",
          division: "Treasury Operations",
          score: 74,
          severity: "High",
          likelihood: "Likely",
          impact: "Medium",
          trend: "up",
        },
        {
          rank: 5,
          title: "Vendor SLA gaps",
          division: "Procurement",
          score: 71,
          severity: "High",
          likelihood: "Possible",
          impact: "Medium",
          trend: "down",
        },
      ],
    },
  },
  {
    id: "s5",
    shortTitle: "Audit Findings",
    notes:
      "Flag that AF-2026-114 is overdue and that both critical findings target the August board submission. Overall closure rate is 61%.",
    content: {
      kind: "audit-findings",
      findings: presentationFindings,
    },
  },
  {
    id: "s6",
    shortTitle: "Management Actions",
    notes:
      "Ask the board to approve the privileged access remediation program and the automated segregation of duties controls. Both actions carry August deadlines aligned to the next board pack.",
    content: {
      kind: "management-actions",
      actions: presentationActions,
      decisions: boardSummary.decisions.map((decision) => ({
        decision: decision.decision,
        owner: decision.owner,
        target: decision.target,
      })),
    },
  },
  {
    id: "s7",
    shortTitle: "Closing",
    notes:
      "Direct discussion toward the two decisions requested on the management actions slide. Reference the full Monthly Operational Risk Report ORR-2026-07 for audit-level detail.",
    content: {
      kind: "closing",
      title: "Thank You",
      subtitle: "Questions & Discussion",
      nextSteps: [
        "Approve the privileged access remediation program by Aug 15",
        "Endorse automated segregation of duties controls by Aug 20",
        "Review vendor SLA monitoring rollout at the September board",
        "Full detail in Monthly Operational Risk Report ORR-2026-07",
      ],
      contact: "Priya Nair — Chief Risk Officer · Meridian Bank",
    },
  },
];
